[Settings]
ID = "Develop-I"
[build]
  # This will be your default build command
  base = "/"
  #command = "npm run build"
  publish = "dist"

# [[redirects]]
#  from = "/"
#  to = "/index.html"
#  status = 200
#  force = true

[[redirects]]
 from = "/*"
 to = "/index.html"
 status = 200
 #force = true